name: Playwright Tests
on:
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install dev dependencies for automation scripts
      run: npm install --save-dev playwright typescript ts-node
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    # - name: Run Playwright tests
    #   run: npx playwright test

    - name: Run individual automation script
      run: npx ts-node src/automation/ScrapeGameCurrentPrice.ts
      env:
        MY_USERNAME: ${{ secrets.MY_USERNAME }}
        MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
    
    - name: Upload artifact after first script
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: Scraped Data for Current game Price games_current_price.json
        path: src/testData/games_current_price.json
        retention-days: 5
        
    - name: Run next automation script if previous passed
      if: ${{ success() }}
      run: npx ts-node src/automation/ComparePrices.ts
      
    - name: Upload artifact after Second script
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: Low Hit Prices for Games
        path: src/testData/low_price_hit.json
        retention-days: 5
        
    - name: Send Low Hit Prices to Discord (pretty)
      if: success()
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        json=$(cat src/testData/low_price_hit.json | jq .)
        curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"\`\`\`json\n$json\n\`\`\`\"}" \
            $DISCORD_WEBHOOK_URL

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 5